Add Rationale draft
rmrk-team/NestingEIP pull request #2
Opened 2022-11-20 23:45 UTC by ThunderDeliverer

The Rationale draft has been added to outline its structure and rough content in each of the sections.

2022-11-21 17:38 UTC, steven2308 commented on README.md
> +     *  child tokens.
This is repeated in the previous line.

2022-11-21 17:38 UTC, steven2308 commented on README.md
> +     *  child tokens.
Same here

2022-11-21 17:39 UTC, steven2308 commented on README.md
> +As this proposal standardizes the nesting of one `NFT` into another, the working title if the proposal was Nesting. In an effort to provide as much information about the proposal we identified the mo
`the working title if the proposal was Nesting` 
This doesn't feel like a correct sentence

2022-11-21 17:40 UTC, steven2308 commented on README.md
> +2. **Why is automatically accepting a child using [EIP-712](./eip-712.md) permit-style signatures not a part of this proposal?**
This could apply not only to accept child but also to other operations as reject and unnest (soon to be transferChild)

2022-11-21 17:42 UTC, steven2308 commented on README.md
> +To avoid race conditions in which the index of a token changes, the expected token ID is included in operations requiring token index, to verify that the token being accessed using the index is the e
We need both the expect contract address and token Id.

2022-11-21 17:44 UTC, steven2308 commented on README.md
> +
Let's mention that the minimum cost of accepting a child increased over 20% and for nest minting over 15%.

2022-11-21 17:45 UTC, steven2308 commented on README.md
> +Another benefit of having bounded child tokens array is to guard against spam and griefing. As minting malisioud or spam tokens could be relatively easy and low-cost, the bounded pending array assure
Typo on `malisioud`

2022-11-21 17:47 UTC, steven2308 commented on README.md
> +A consideration tied to this issue was also how to make sure, that a legitimate token is not accidentally rejected when clearing the pending child tokens array. We added the maximum pending children
Actually we did this only for resources and I just realized so. Added a note to add it here as well.

2022-11-21 17:47 UTC, steven2308 commented on README.md
> +A consideration tied to this issue was also how to make sure, that a legitimate token is not accidentally rejected when clearing the pending child tokens array. We added the maximum pending children
Typo on `cearing`

2022-11-21 17:48 UTC, steven2308 commented on README.md
> +The proposal enforces that a parent token can't ve nested into one of its child token, or downstream child tokens for that matter. A parent token and its children are all managed by the parent token'
I wouldn't mention this is possible because I don't think it is. A loop would make it impossible to get the root owner so nothing will work if you bypass the check.

2022-11-21 17:49 UTC, steven2308 requested changes
Added comments :smiley:

2022-11-21 22:01 UTC, ThunderDeliverer commented on README.md
> +2. **Why is automatically accepting a child using [EIP-712](./eip-712.md) permit-style signatures not a part of this proposal?**
I think I might not have gotten into enough detail here, or that this should have been broken down into two points.

1. Automatic acceptance without anything fancy (just whitelist some smart contract collection and anything from there is automatically accepted)
2. Using EIP-712 permits which does not require any kind of whitelisting, just correct `r`, `s` and `v` values that any nest operation can pass and the token is then accepted.

Maybe 2nd could be too abstract to include in the proposal, but I think it would add to the weight of it if we note that we considered both.

2022-11-21 22:01 UTC, ThunderDeliverer commented on README.md
> +As this proposal standardizes the nesting of one `NFT` into another, the working title if the proposal was Nesting. In an effort to provide as much information about the proposal we identified the mo
Just a typo :D

2022-11-22 14:02 UTC, steven2308 commented on README.md
> +2. **Why is automatically accepting a child using [EIP-712](./eip-712.md) permit-style signatures not a part of this proposal?**
Let's do 2 points please. I think we should mention the no-712 rationale, but basically the same we did for MA.

2022-11-22 14:06 UTC, steven2308 commented on README.md
> +The proposal enforces that a parent token can't ve nested into one of its child token, or downstream child tokens for that matter. A parent token and its children are all managed by the parent token'
I'm not saying it couldn't be useful, but it is not doable. Once a loop is created, every operation that needs to check ownership will fall into out of gas since it's an infinite check up. Let's not consider it here

2022-11-22 14:06 UTC, ThunderDeliverer commented on README.md
> +2. **Why is automatically accepting a child using [EIP-712](./eip-712.md) permit-style signatures not a part of this proposal?**
I realised after addressing the `Multi-Child Storage Schema` and `Propose-Commit pattern for child token management` that the point number 1 has already been addressed. I can modify this section a bit to be clearer, to address the point number 2, but I think we are good 👌

2022-11-22 14:07 UTC, ThunderDeliverer commented on README.md
> +The proposal enforces that a parent token can't ve nested into one of its child token, or downstream child tokens for that matter. A parent token and its children are all managed by the parent token'
Ok, I'll remove it then 👌

2022-11-22 16:34 UTC, steven2308 commented on README.md
> +     * @param destinationId ID of the token to receive this child token (should be 0 if the destination is not a token)
I think it is MUST instead of SHOULD here.

2022-11-22 16:38 UTC, steven2308 commented on README.md
> +As this proposal standardizes the nesting of one `NFT` into another, the working title of the proposal was Nesting. In an effort to provide as much information about the proposal we identified the mo
I think this first part is not needed:
`As this proposal standardizes the nesting of one `NFT` into another, the working title of the proposal was Nesting`

2022-11-22 16:54 UTC, steven2308 requested changes
I was very critic, but I think we're really close, great job!

2022-11-22 16:54 UTC, steven2308 commented on README.md
> +To reduce the gas consumption. If the token ID was used to find which token to accept or reject, iteration over arrays would be required and the cost of the operation would depend on the size of the
...per token need... -> per token **needs**

2022-11-22 16:54 UTC, steven2308 commented on README.md
> +To avoid race conditions in which the index of a token changes, the expected token ID as well as the expected token's collection smart contract is included in operations requiring token index, to ver
the expected token -> the expected one. We're already talking about the token.

2022-11-22 16:54 UTC, steven2308 commented on README.md
> +Implementation that would internally keep track of indices using mapping was attempted. The minimum cost of accepting a child token was increased by over 20% and the cost of minting has increased for
We're using "by over" and then "for over".  I think by is the correct one.

2022-11-22 16:54 UTC, steven2308 commented on README.md
> +The pending child tokens array is not meant to be a buffer to collect the tokens that the user wants to have, but not as active children. It is meant to be an easily traversible list of child token c
tokens that the user wants to have -> tokens that the NFT has received.

2022-11-22 16:54 UTC, steven2308 commented on README.md
> +The pending child tokens array is not meant to be a buffer to collect the tokens that the user wants to have, but not as active children. It is meant to be an easily traversible list of child token c
This paragraph in general is a bit confusing IMO, going in circles. I mean I get it, but I already know that you're trying to say. I wonder if someone new can get it easily with this.

2022-11-22 16:54 UTC, steven2308 commented on README.md
> +The proposal enforces that a parent token can't be nested into one of its child token, or downstream child tokens for that matter. A parent token and its children are all managed by the parent token'
Used or utilized seems redundant.

2022-11-22 16:54 UTC, steven2308 commented on README.md
> +Child tokens are stored within two arrays, a pending child tokens array and an active child tokens array. The tokens are accessed using indices. This assures the most efficien way of accessing the ch
Typo: efficien -> efficient

2022-11-22 16:54 UTC, steven2308 commented on README.md
> +Child tokens are stored within two arrays, a pending child tokens array and an active child tokens array. The tokens are accessed using indices. This assures the most efficien way of accessing the ch
accessing the children tokens. I think

2022-11-22 16:54 UTC, steven2308 commented on README.md
> +Using a single array containing pending nad active children would require additional information required to be stored in the storage. More specifically a value indicating wheteher the child token is
nad -> and

2022-11-22 16:54 UTC, steven2308 commented on README.md
> +### Multi-Child Storage Schema
I find this title very confusing. We've never talked about "Multi-Child". 
I also feel it's mostly repeating from the 4 point. I would just remove this section and maybe add what's missing into point 4.

2022-11-22 16:54 UTC, steven2308 commented on README.md
> +The limitation that only the root owner can accept the child tokens also introduces a trust inherent to the proposal. This ensures that the root owner of the token has full control over the token. No
Noone -> No one

2022-11-22 21:59 UTC, ThunderDeliverer commented on README.md
> +Child tokens are stored within two arrays, a pending child tokens array and an active child tokens array. The tokens are accessed using indices. This assures the most efficien way of accessing the ch
I think it's child tokens, because of tokens already being plural. We established that the "child token" is an item, so the plural of it should be of the whole item (hopefully). In any case, I think that one oof the editors will alert us if I'm wrong :p

2022-11-22 22:09 UTC, ThunderDeliverer commented on README.md
> +### Multi-Child Storage Schema
Makes sense. I think that all of the important info is already addresed in the point 4. I'll just remove this section.

2022-11-22 22:20 UTC, ThunderDeliverer commented on README.md
> +The pending child tokens array is not meant to be a buffer to collect the tokens that the user wants to have, but not as active children. It is meant to be an easily traversible list of child token c
I wanted to get the message across, that the root owner might want some pending tokens to remain there for some indeterminable time in the future (like when you keep some items in your inventory when you are playing a game, just in case you might need them in the future, but then you finish the game and the items are still there).

I think that the changes I made to the paragraph properly illustrate my point now

2022-11-22 22:20 UTC, ThunderDeliverer commented on README.md
> +Implementation that would internally keep track of indices using mapping was attempted. The minimum cost of accepting a child token was increased by over 20% and the cost of minting has increased for
I agree :D

2022-11-22 22:21 UTC, ThunderDeliverer commented on README.md
> +To avoid race conditions in which the index of a token changes, the expected token ID as well as the expected token's collection smart contract is included in operations requiring token index, to ver
Yeah, I think that the word of the day is definitely `token` :'D

2022-11-22 22:22 UTC, ThunderDeliverer commented on README.md
> +To reduce the gas consumption. If the token ID was used to find which token to accept or reject, iteration over arrays would be required and the cost of the operation would depend on the size of the
The need is referring to the arrays, so I think this is the correct form (they need to ..)

2022-11-22 22:23 UTC, ThunderDeliverer commented on README.md
> +As this proposal standardizes the nesting of one `NFT` into another, the working title of the proposal was Nesting. In an effort to provide as much information about the proposal we identified the mo
Sure, might have been redundant. I added it in an effort to address all parts of the title, but this might have been an overkill :'D

2022-11-22 22:24 UTC, ThunderDeliverer commented on README.md
> +     * @param destinationId ID of the token to receive this child token (should be 0 if the destination is not a token)
Nice catch!

2022-11-22 22:26 UTC, ThunderDeliverer commented
> I was very critic, but I think we're really close, great job!

I think this is the right thing to do. When writing an EIP the reviewer always has to assume the role of the devil's advocate. Good job! 👌 🙌 😄

2022-11-23 00:42 UTC, steven2308 commented on README.md
> +Child tokens are stored within two arrays, a pending child tokens array and an active child tokens array. The tokens are accessed using indices. This assures the most efficien way of accessing the ch
Fair enough 💪🏻

2022-11-23 00:46 UTC, steven2308 commented on README.md
> +To reduce the gas consumption. If the token ID was used to find which token to accept or reject, iteration over arrays would be required and the cost of the operation would depend on the size of the
I insist, the subject here is "a list". A list needs to be maintained.

2022-11-23 00:52 UTC, steven2308 commented on README.md
> +To reduce the gas consumption. If the token ID was used to find which token to accept or reject, iteration over arrays would be required and the cost of the operation would depend on the size of the
Let's just change it for "Lists of active and pending children per token need to be maintained, ..."

2022-11-23 07:40 UTC, ThunderDeliverer commented on README.md
> +To reduce the gas consumption. If the token ID was used to find which token to accept or reject, iteration over arrays would be required and the cost of the operation would depend on the size of the
Yeah, my bad, you were right 🙈 I think that your last proposal was the best version of this sentence. I'll update it 👌

2022-11-23 07:44 UTC, ThunderDeliverer commented on README.md
> +To reduce the gas consumption. If the token ID was used to find which token to accept or reject, iteration over arrays would be required and the cost of the operation would depend on the size of the
```suggestion
To reduce the gas consumption. If the token ID was used to find which token to accept or reject, iteration over arrays would be required and the cost of the operation would depend on the size of the active or pending children arrays. With the index, the cost is fixed. Lists of active and pending children per token need to be maintained, since methods to get them are part of the proposed interface.
```

2022-11-23 07:44 UTC, ThunderDeliverer commented on README.md
> +child token's role is only to be able to be `Nestable` and support a token owning it. This is how we landed on the `Parent-Centered` part of the title.
```suggestion
In an effort to provide as much information about the proposal we identified the most important aspect of the proposal; the parent centered control over nesting. The child token's role is only to be able to be `Nestable` and support a token owning it. This is how we landed on the `Parent-Centered` part of the title.
```

2022-11-23 07:46 UTC, merged